name: kpksdev
root: ~/Repos/lah-rb.github.io

windows:
  - hub:
      layout: tiled
      panes:
        - sleep 2 && jekyll server --host=0.0.0.0 --livereload --watch
        - jekyll build --watch
        - tailwindcss -i ./assets/css/input.css -o ./assets/css/output.css --watch
        - sleep 4 && firefox http://localhost:4000 && clear
