name: kpksdev
root: ~/Repos/lah-rb.github.io

windows:
  - hub:
      layout: tiled
      panes:
        - sleep 1 && jekyll server --host=0.0.0.0 --livereload --watch
        - jekyll build --watch
        - tailwindcss -i ./assets/css/input.css -o ./assets/css/output.css --watch
        - sleep 2 && nohup firefox http://localhost:4000 >/dev/null 2>&1 &

#run from home directory with kpksdev or tmuxinator kpksdev in lah-rb.github.io