// Load Workbox from local vendored copy (generated by: deno task setup:workbox)
importScripts('/assets/js/workbox/workbox-v7.3.0/workbox-sw.js');

// Tell workbox-sw to load all modules from local path instead of CDN
workbox.setConfig({ modulePathPrefix: '/assets/js/workbox/workbox-v7.3.0/' });

const { setCacheNameDetails, clientsClaim } = workbox.core;
const { precacheAndRoute, cleanupOutdatedCaches } = workbox.precaching;
const { registerRoute } = workbox.routing;
const { NetworkFirst, StaleWhileRevalidate, CacheFirst } = workbox.strategies;
const { ExpirationPlugin } = workbox.expiration;

// ============================================
// CACHE NAMING
// ============================================
// Static cache names — no version hash so runtime caches persist across deploys.
// Precaching already handles versioning via file-revision hashes.
setCacheNameDetails({ prefix: 'kipukas-pwa' });

// ============================================
// LIFECYCLE: controlled skipWaiting via postMessage
// ============================================
// Do NOT call self.skipWaiting() automatically.
// The client (pwa-update-handler.js) will send a SKIP_WAITING message
// when the user chooses to update, giving them control over the timing.

// Track whether the PWA has been installed (persists for the SW lifetime).
let pwaInstalled = false;

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }

  // install_pwa.html notifies us when the user completes a PWA install.
  if (event.data && event.data.type === 'PWA_INSTALLED') {
    pwaInstalled = true;
  }

  // install_pwa.html asks us on page load whether the PWA was already installed.
  // Responds on the provided MessageChannel port.
  if (event.data && event.data.type === 'PWA_INSTALL_CHECK') {
    if (event.ports && event.ports[0]) {
      event.ports[0].postMessage({ installed: pwaInstalled });
    }
  }
});

clientsClaim();

// ============================================
// PRECACHING
// ============================================
// The placeholder below is replaced at build time by workbox-cli
// injectManifest with the list of revisioned URLs.
precacheAndRoute(self.__WB_MANIFEST, {
  ignoreURLParametersMatching: [/^utm_/, /^fbclid$/],
});
cleanupOutdatedCaches();

// ============================================
// WASM API ROUTES — relay /api/* to page → Web Worker → WASM
// ============================================
// HTMX makes real fetch() calls to /api/* endpoints.
// This route intercepts them and relays to the page's kipukas-api.js bridge,
// which forwards to the WASM Web Worker for processing.
// A MessageChannel provides a direct response path from the worker back to here.
const wasmApiMatcher = ({url}) => url.pathname.startsWith('/api/');
const wasmApiHandler = async ({request, event}) => {
    const client = await self.clients.get(event.clientId);
    if (!client) {
      return new Response(
        '<span class="text-kip-red">No controlling page found for WASM relay</span>',
        { status: 503, headers: { 'Content-Type': 'text/html; charset=utf-8' } }
      );
    }

    const url = new URL(request.url);

    // Read request body for POST/PUT/PATCH methods (Phase 2: needed for future POST routes)
    const body = ['POST', 'PUT', 'PATCH'].includes(request.method)
      ? await request.text()
      : '';

    return new Promise((resolve, reject) => {
      const channel = new MessageChannel();

      // Timeout: if the worker doesn't respond in 5s, fail gracefully
      const timeout = setTimeout(() => {
        reject(new Response(
          '<span class="text-kip-red">WASM request timed out</span>',
          { status: 504, headers: { 'Content-Type': 'text/html; charset=utf-8' } }
        ));
      }, 5000);

      channel.port1.onmessage = (msg) => {
        clearTimeout(timeout);
        resolve(new Response(msg.data.html, {
          status: msg.data.ok ? 200 : 500,
          headers: { 'Content-Type': 'text/html; charset=utf-8' },
        }));
      };

      // Send the request details + one end of the channel to the page.
      // The page's kipukas-api.js will transfer port2 to the WASM Web Worker.
      client.postMessage({
        type: 'WASM_REQUEST',
        method: request.method,
        pathname: url.pathname,
        search: url.search,
        body: body,
      }, [channel.port2]);
    });
  };

// Register for all HTTP methods (Workbox registerRoute defaults to GET only)
registerRoute(wasmApiMatcher, wasmApiHandler);         // GET
registerRoute(wasmApiMatcher, wasmApiHandler, 'POST');  // POST
registerRoute(wasmApiMatcher, wasmApiHandler, 'PUT');   // PUT
registerRoute(wasmApiMatcher, wasmApiHandler, 'PATCH'); // PATCH

// ============================================
// JXL IMAGE ROUTE — decode .jxl via WASM, serve a renderable BMP
// ============================================
// Card art is stored as a single progressive .jxl per card. The browser can't
// decode JXL (here), so we intercept every .jxl request and route the bytes
// through the same page → Web Worker → WASM bridge used for /api/*.
//
// Query params (emitted by the card renderer / layout):
//   ?p=<bytes>  preview prefix length — Range-fetch only this many leading
//               bytes (the DC/low-res image) instead of the whole file.
//   ?d=<px>     downscale target — longest output side in pixels (0 = full).
//
// Decoded previews are cached (small, hit repeatedly on grid scroll-back);
// full images cache only the small raw .jxl for offline and re-decode on view.
const DECODED_CACHE = 'kipukas-images-decoded';
const RAW_JXL_CACHE = 'kipukas-jxl';

// In-flight decode de-duplication: the card detail page requests the same full
// .jxl three times at once (two <img> + one CSS background). Collapse identical
// concurrent requests onto a single decode and share the resulting bytes.
const jxlInflight = new Map();

const jxlMatcher = ({ url }) => url.pathname.endsWith('.jxl');

/// Fetch + decode the bytes for one .jxl request, returning the BMP bytes.
async function decodeJxlRequest(request, event) {
  const url = new URL(request.url);
  const previewBytes = parseInt(url.searchParams.get('p') || '0', 10);
  const maxDim = parseInt(url.searchParams.get('d') || '0', 10);
  const isPreview = previewBytes > 0;

  // Fetch the .jxl bytes — a Range prefix for previews, the whole file
  // otherwise. Cache the (small) raw full file for offline re-decode.
  const assetUrl = url.origin + url.pathname;
  const rawCache = await caches.open(RAW_JXL_CACHE);
  let buf;
  try {
    const opts = isPreview ? { headers: { Range: `bytes=0-${previewBytes - 1}` } } : {};
    const net = await fetch(assetUrl, opts);
    if (net.ok || net.status === 206) {
      if (!isPreview) {
        try { await rawCache.put(assetUrl, net.clone()); } catch (_e) { /* quota */ }
      }
      buf = await net.arrayBuffer();
    }
  } catch (_e) { /* offline — fall through to cache */ }
  if (!buf) {
    const cachedRaw = await rawCache.match(assetUrl);
    if (cachedRaw) buf = await cachedRaw.arrayBuffer(); // decode full even for preview
  }
  if (!buf) return null;

  // Relay bytes to the page → Web Worker → WASM for decode.
  const client =
    (event.clientId && (await self.clients.get(event.clientId))) ||
    (await self.clients.matchAll({ type: 'window' }))[0];
  if (!client) return { raw: buf }; // no page to decode through (very first load)

  const bmp = await new Promise((resolve, reject) => {
    const channel = new MessageChannel();
    const timeout = setTimeout(() => reject(new Error('JXL decode timed out')), 15000);
    channel.port1.onmessage = (msg) => {
      clearTimeout(timeout);
      msg.data.ok ? resolve(msg.data.bytes) : reject(new Error(msg.data.error));
    };
    client.postMessage(
      { type: 'WASM_DECODE_JXL', bytes: buf, maxDim },
      [buf, channel.port2],
    );
  });
  return { bmp, isPreview };
}

const jxlHandler = async ({ request, event }) => {
  const isPreview = new URL(request.url).searchParams.has('p');

  // 1. Decoded-preview cache (keyed by the full request incl. query).
  const decodedCache = await caches.open(DECODED_CACHE);
  if (isPreview) {
    const hit = await decodedCache.match(request);
    if (hit) return hit;
  }

  // 2. Decode (de-duplicating identical concurrent requests).
  const key = request.url;
  let result;
  try {
    if (jxlInflight.has(key)) {
      result = await jxlInflight.get(key);
    } else {
      const p = decodeJxlRequest(request, event);
      jxlInflight.set(key, p);
      try { result = await p; } finally { jxlInflight.delete(key); }
    }
  } catch (_e) {
    return Response.error();
  }
  if (!result) return Response.error();

  // 3. Build the response. Each caller gets a fresh Response from the bytes.
  if (result.raw) {
    return new Response(result.raw, { headers: { 'Content-Type': 'image/jxl' } });
  }
  const resp = new Response(result.bmp, {
    status: 200,
    headers: { 'Content-Type': 'image/bmp' },
  });
  if (result.isPreview) {
    try { await decodedCache.put(request, resp.clone()); } catch (_e) { /* quota */ }
  }
  return resp;
};

registerRoute(jxlMatcher, jxlHandler);

// ============================================
// RUNTIME CACHING STRATEGIES
// ============================================

// Strategy 1: HTML Pages — NetworkFirst (fresh content is critical)
registerRoute(
  /\.(?:html)$/,
  new NetworkFirst({
    cacheName: 'kipukas-pages',
    networkTimeoutSeconds: 3,
    matchOptions: { ignoreSearch: true },
    plugins: [
      {
        cacheWillUpdate: async ({ response }) =>
          response && response.status === 200 ? response : null,
      },
    ],
  })
);

// Strategy 2: Static Assets (CSS, JS, WASM) — StaleWhileRevalidate
registerRoute(
  /\.(?:css|js|wasm)$/,
  new StaleWhileRevalidate({
    cacheName: 'kipukas-assets',
    plugins: [
      {
        cacheWillUpdate: async ({ response }) =>
          response && response.status === 200 ? response : null,
      },
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
        purgeOnQuotaError: true,
      }),
    ],
  })
);

// Strategy 3: Images — CacheFirst (images rarely change)
registerRoute(
  /\.(?:png|jpg|jpeg|svg|gif|webp|ico)$/,
  new CacheFirst({
    cacheName: 'kipukas-images',
    plugins: [
      {
        cacheWillUpdate: async ({ response }) =>
          response && response.status === 200 ? response : null,
      },
      new ExpirationPlugin({
        maxEntries: 500,
        maxAgeSeconds: 60 * 24 * 60 * 60, // 60 days
        purgeOnQuotaError: true,
      }),
    ],
  })
);

// Strategy 4: Google Fonts — CacheFirst with long expiration
registerRoute(
  /^https:\/\/fonts\.(?:googleapis|gstatic)\.com\/.*/i,
  new CacheFirst({
    cacheName: 'kipukas-fonts',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
);

// ============================================
// CLEANUP: remove old versioned runtime caches from the previous setup
// ============================================
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) =>
      Promise.all(
        cacheNames
          .filter((name) => {
            // Delete any old runtime caches that contain a version hash
            // (the old format was kipukas-{type}-{hash}_{date})
            const isOldVersionedCache =
              name.startsWith('kipukas-') &&
              /kipukas-(?:pages|assets|images|fonts)-[a-f0-9]{64}/.test(name);
            // Also delete the old "my-app-cache-" prefix from the backup config
            const isLegacyCache = name.startsWith('my-app-cache-');
            return isOldVersionedCache || isLegacyCache;
          })
          .map((name) => {
            console.log('[SW] Deleting old cache:', name);
            return caches.delete(name);
          })
      )
    )
  );
});
