/**
 * build-card-catalog.ts
 *
 * Reads all _posts/*.html front matter and generates a Rust source file
 * (kipukas-server/src/cards_generated.rs) containing the card catalog
 * as a static array. This is compiled into the WASM binary so the
 * /api/cards route can filter and paginate without any runtime data loading.
 *
 * Run: deno task build:card-catalog
 */

import { walk } from 'jsr:@std/fs@1/walk';
import { join } from 'jsr:@std/path@1';

interface CardMeta {
  slug: string; // permalink without slashes
  title: string;
  layout: string;
  img_name: string;
  img_alt: string;
  tags: string;
  genetic_disposition: string | null;
  motivation: string | null;
  habitat: string | null;
  url: string; // permalink as-is (e.g. /frost_tipped_arctic_otter/)
}

function parseFrontMatter(content: string): Record<string, string> {
  const match = content.match(/^---\s*\n([\s\S]*?)\n---/);
  if (!match) return {};

  const fm: Record<string, string> = {};
  for (const line of match[1].split('\n')) {
    // Simple key: value parsing (handles quoted and unquoted values)
    const kvMatch = line.match(/^(\w+):\s*"?(.*?)"?\s*$/);
    if (kvMatch) {
      fm[kvMatch[1]] = kvMatch[2];
    }
  }
  return fm;
}

function escapeRust(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function optionStr(val: string | undefined | null): string {
  if (!val || val.trim() === '') return 'None';
  return `Some("${escapeRust(val.trim())}")`;
}

async function main() {
  const postsDir = join(Deno.cwd(), '_posts');
  const cards: CardMeta[] = [];

  for await (const entry of walk(postsDir, { exts: ['.html'], maxDepth: 1 })) {
    if (!entry.isFile) continue;

    const content = await Deno.readTextFile(entry.path);
    const fm = parseFrontMatter(content);

    if (!fm.permalink || !fm.title || !fm.layout || !fm.img_name) {
      console.warn(`Skipping ${entry.name}: missing required front matter`);
      continue;
    }

    const slug = fm.permalink.replace(/\//g, '');

    cards.push({
      slug,
      title: fm.title,
      layout: fm.layout,
      img_name: fm.img_name,
      img_alt: fm.img_alt || '',
      tags: fm.tags || '',
      genetic_disposition: fm.genetic_disposition || null,
      motivation: fm.motivation || null,
      habitat: fm.habitat || null,
      url: fm.permalink,
    });
  }

  // Sort alphabetically by title (matching current Jekyll sort:title)
  cards.sort((a, b) => a.title.localeCompare(b.title));

  // Generate Rust source
  const lines: string[] = [
    '// AUTO-GENERATED by scripts/build-card-catalog.ts',
    '// Do not edit manually. Re-run: deno task build:card-catalog',
    '',
    '#[derive(Debug, Clone)]',
    'pub struct Card {',
    '    pub slug: &\'static str,',
    '    pub title: &\'static str,',
    '    pub layout: &\'static str,',
    '    pub img_name: &\'static str,',
    '    pub img_alt: &\'static str,',
    '    pub tags: &\'static str,',
    '    pub genetic_disposition: Option<&\'static str>,',
    '    pub motivation: Option<&\'static str>,',
    '    pub habitat: Option<&\'static str>,',
    '    pub url: &\'static str,',
    '}',
    '',
    `pub const CARD_COUNT: usize = ${cards.length};`,
    '',
    'pub static CARDS: [Card; CARD_COUNT] = [',
  ];

  for (const card of cards) {
    lines.push('    Card {');
    lines.push(`        slug: "${escapeRust(card.slug)}",`);
    lines.push(`        title: "${escapeRust(card.title)}",`);
    lines.push(`        layout: "${escapeRust(card.layout)}",`);
    lines.push(`        img_name: "${escapeRust(card.img_name)}",`);
    lines.push(`        img_alt: "${escapeRust(card.img_alt)}",`);
    lines.push(`        tags: "${escapeRust(card.tags)}",`);
    lines.push(`        genetic_disposition: ${optionStr(card.genetic_disposition)},`);
    lines.push(`        motivation: ${optionStr(card.motivation)},`);
    lines.push(`        habitat: ${optionStr(card.habitat)},`);
    lines.push(`        url: "${escapeRust(card.url)}",`);
    lines.push('    },');
  }

  lines.push('];');
  lines.push('');

  const outPath = join(Deno.cwd(), 'kipukas-server', 'src', 'cards_generated.rs');
  await Deno.writeTextFile(outPath, lines.join('\n'));

  console.log(`[build-card-catalog] Generated ${cards.length} cards → ${outPath}`);
}

main();